- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    rgn: us-east-1
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: vpc-by-ansible
      cidr_block: 10.0.0.0/26
      region: "{{rgn}}"
      state: present
      aws_access_key: AKIAUDV7DUMMYUZR7LH
      aws_secret_key: RN+25TJ6DUMMY/1mteUWQVJZjlBSp
      resource_tags:
        type: ws-vpc
    register: vpc

